/**
 * The setup slice: the player list, the role composition, the deal, and the
 * pass-the-phone role reveal.
 *
 * Every function here is pure — ids and seeds arrive as arguments so a deal can be
 * replayed exactly from the state the app stored.
 */

import { shuffle } from "src/lib/game/shuffle";
import type { GameState, Player } from "src/lib/game/types";
import { Phase, RoleId } from "src/lib/game/types";

/** Why the chosen composition does not cover the table. */
export enum RoleCountIssueKind {
  TooFewRoles = "too-few-roles",
  TooManyRoles = "too-many-roles",
}

/** A mismatch between the players at the table and the cards chosen for them. */
export interface RoleCountIssue {
  kind: RoleCountIssueKind;
  playerCount: number;
  roleCount: number;
}

/**
 * Builds an empty game sitting on the setup screen.
 * @returns A fresh game state with no players, no cards chosen and nothing resolved.
 */
export function createInitialState(): GameState {
  return {
    phase: Phase.Setup,
    players: [],
    roleCounts: {
      [RoleId.Werewolf]: 0,
      [RoleId.Villager]: 0,
      [RoleId.Seer]: 0,
      [RoleId.Doctor]: 0,
      [RoleId.Witch]: 0,
      [RoleId.Hunter]: 0,
      [RoleId.Cupid]: 0,
      [RoleId.Fool]: 0,
    },
    seed: 0,
    nightNumber: 0,
    night: {
      wolfVotes: {},
      protectedId: null,
      inspectedId: null,
      healsVictim: false,
      poisonTargetId: null,
      loverIds: null,
    },
    revealIndex: 0,
    nightOrderIds: [],
    nightCursor: 0,
    dawnDeaths: [],
    dayVotes: {},
    revoteCandidateIds: [],
    loverIds: null,
    witchHealAvailable: true,
    witchPoisonAvailable: true,
    lastProtectedId: null,
    hunterTargetId: null,
    pendingHeartbreakId: null,
    winner: null,
  };
}

/**
 * Starts a fresh game with the same people.
 *
 * The table and the deck are the tedious part to re-enter, so they survive; every
 * card, death and vote from the finished game does not.
 * @param state - The game being left behind.
 * @returns A game back on the setup screen, seated and dealt-ready.
 */
export function resetGame(state: GameState): GameState {
  return {
    ...createInitialState(),
    players: state.players.map((player) => ({
      ...player,
      role: null,
      isAlive: true,
    })),
    roleCounts: state.roleCounts,
  };
}

/**
 * Adds a player to the table.
 * @param state - The current game state; never mutated.
 * @param id - The player's id, generated by the caller so the engine stays pure.
 * @param name - The player's display name.
 * @returns A new state with the player appended.
 */
export function addPlayer(
  state: GameState,
  id: string,
  name: string,
): GameState {
  return withAutoVillagers({
    ...state,
    players: [...state.players, { id, name, role: null, isAlive: true }],
  });
}

/**
 * Removes a player from the table.
 * @param state - The current game state; never mutated.
 * @param playerId - The id of the player to drop.
 * @returns A new state without that player.
 */
export function removePlayer(state: GameState, playerId: string): GameState {
  return withAutoVillagers({
    ...state,
    players: state.players.filter((player) => player.id !== playerId),
  });
}

/**
 * Refills the villager count so the deck always covers exactly the table.
 *
 * Villagers are the filler role, so the host picks the specials and never does
 * the arithmetic — which is why the villager count has no control of its own.
 * @param state - The state whose composition should be rebalanced.
 * @returns A new state with the villager count derived from the rest.
 */
function withAutoVillagers(state: GameState): GameState {
  const specialists = Object.entries(state.roleCounts)
    .filter(([role]) => role !== RoleId.Villager)
    .reduce((total, [, count]) => total + count, 0);

  return {
    ...state,
    roleCounts: {
      ...state.roleCounts,
      [RoleId.Villager]: Math.max(0, state.players.length - specialists),
    },
  };
}

/**
 * Sets how many of a role are in play, then refills the villagers around it.
 * @param state - The current game state; never mutated.
 * @param role - The role being adjusted.
 * @param count - How many of that role to deal.
 * @returns A new state with the deck rebalanced.
 */
export function setRoleCount(
  state: GameState,
  role: RoleId,
  count: number,
): GameState {
  return withAutoVillagers({
    ...state,
    roleCounts: { ...state.roleCounts, [role]: count },
  });
}

/**
 * Checks whether the chosen cards cover exactly the players at the table.
 * @param state - The current game state.
 * @returns The mismatch, or null when the counts match.
 */
export function getRoleCountIssue(state: GameState): RoleCountIssue | null {
  const playerCount = state.players.length;
  const roleCount = Object.values(state.roleCounts).reduce(
    (total, count) => total + count,
    0,
  );

  if (roleCount === playerCount) {
    return null;
  }

  return {
    kind:
      roleCount < playerCount
        ? RoleCountIssueKind.TooFewRoles
        : RoleCountIssueKind.TooManyRoles,
    playerCount,
    roleCount,
  };
}

/**
 * Deals one shuffled card to each player and opens the role reveal.
 * @param state - The current game state; never mutated.
 * @param seed - Seed selecting the deal, stored so the game can be replayed.
 * @returns A new state with every player holding a role, on the reveal screen.
 */
export function dealRoles(state: GameState, seed: number): GameState {
  // Built in enum order so the same seed always produces the same deal.
  const deck: RoleId[] = Object.values(RoleId).flatMap((role) =>
    Array.from({ length: state.roleCounts[role] }, () => role),
  );
  const shuffled = shuffle(deck, seed);

  return {
    ...state,
    players: state.players.map((player, index) => ({
      ...player,
      role: shuffled[index] ?? null,
    })),
    phase: Phase.RoleReveal,
    revealIndex: 0,
    seed,
  };
}

/**
 * Finds whose turn it is to look at their own card.
 * @param state - The current game state.
 * @returns The player at the reveal cursor, or null once everyone has looked.
 */
export function getRevealPlayer(state: GameState): Player | null {
  return state.players[state.revealIndex] ?? null;
}

/**
 * Passes the phone to the next player, starting night one after the last of them.
 * @param state - The current game state; never mutated.
 * @returns A new state with the reveal cursor advanced.
 */
export function revealNextPlayer(state: GameState): GameState {
  const nextIndex = state.revealIndex + 1;
  const everyoneHasLooked = nextIndex >= state.players.length;

  return {
    ...state,
    revealIndex: nextIndex,
    // The last player handing the phone back is what starts night one.
    phase: everyoneHasLooked ? Phase.Night : state.phase,
    nightNumber: everyoneHasLooked ? 1 : state.nightNumber,
  };
}
